version: '3.6'
services:
  k8-test-data:
    image: k8-test-data
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MINIO_URL: minio
      MINIO_ACCESS_KEY: minio1
      MINIO_SECRET_KEY: minio1@123
    ports:
      - 5000:5000

  minio:
    image: minio/minio:RELEASE.2020-09-08T23-05-18Z
    volumes:
      - data1-1:/data
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: minio1
      MINIO_SECRET_KEY: minio1@123
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  data1-1: